import { useMemo, useState } from 'react'
import type { MouseEvent } from 'react'
import { evaluatePrototypeData, usePrototypeState } from '../data/prototypeStore'
import type { EvaluationResult, PrototypeState, TraceSource } from '../data/mockData'

type Props = { onNavigate: (event: MouseEvent<HTMLAnchorElement>, path: string) => void }
export type DatasetRecord = { timestamp: string; sourceIp: string; destinationIp: string; protocol: string; sourcePort: number; destinationPort: number; packetCount: number; byteCount: number; connectionCount: number; mqttPublishCount: number; mqttSubscribeCount: number; loginAttempt: number; sessionDuration: number; topic: string; scenarioId: string; attackType: string; label: 'Normal' | 'Attack' | 'Unknown'; source: TraceSource }
const models = ['Logistic Regression', 'Decision Tree', 'Random Forest', 'XGBoost']
const metricKeys = ['accuracy', 'precision', 'recall', 'f1'] as const

function latestResult(results: EvaluationResult[]) { return results.at(-1) }
function metricValue(result: EvaluationResult | undefined, key: 'validity' | 'similarity' | 'diversity' | 'novelty' | 'mlUtility') { return result ? result[key] : 0 }

export function EvaluationPage({ onNavigate }: Props) {
  const state = usePrototypeState()
  const result = latestResult(state.evaluationResults)
  const validCount = state.generatedBehaviors.filter((generation) => generation.validation === 'Passed').length
  const invalidCount = state.generatedBehaviors.filter((generation) => generation.validation === 'Rejected').length
  const validationCount = validCount + invalidCount
  const invalidRate = validationCount ? Math.round(invalidCount / validationCount * 100) : 0
  const summary = [
    ['Validity', metricValue(result, 'validity'), result ? `${validCount} valid · ${invalidCount} invalid` : 'Run an evaluation after validation'],
    ['Similarity', metricValue(result, 'similarity'), 'Observed vs generated'],
    ['Diversity', metricValue(result, 'diversity'), 'Unique generated sequences'],
    ['Novelty', metricValue(result, 'novelty'), 'Transitions absent from observed'],
    ['ML Utility', metricValue(result, 'mlUtility'), 'Estimated model uplift'],
  ] as const
  const charts = result ? [['Action distribution', result.actionSimilarity], ['Transition distribution', result.transitionSimilarity], ['Session length', result.lengthSimilarity], ['Inter-event timing', result.timingSimilarity]] as const : []
  return <div className="phase10-page">
    <section className="card phase10-overview"><div><span className="section-kicker">TRACE-DRIVEN EVALUATION</span><h2>Generated behavior quality</h2><p>Metrics are computed from observed events, linked behavioral sequences, generated actions and replay traces.</p></div><div className="phase10-overview-meta"><span><small>OBSERVED EVENTS</small><strong>{state.traceEvents.filter((event) => event.source === 'observed_real' || event.source === 'simulated').length}</strong></span><span><small>GENERATED ACTIONS</small><strong>{state.generatedBehaviors.reduce((n, item) => n + item.generatedActions.length, 0)}</strong></span><span><small>REPLAY TRACE ROWS</small><strong>{state.generatedTraces.length}</strong></span></div></section>
    <section className="phase10-metrics">{summary.map(([label, value, detail]) => <article className="card phase10-metric" key={label}><span>{label}</span><strong>{result ? `${value}%` : '—'}</strong><div className="phase10-meter"><i style={{ width: `${value}%` }} /></div><small>{detail}</small></article>)}</section>
    <section className="card phase10-panel"><div className="phase10-heading"><div><span className="section-kicker">VALIDATION COHORT</span><h2>Generated sequence validity</h2><p>Constraint results are read from the Validator records.</p></div><button className="button button-primary" disabled={!state.generatedBehaviors.length} onClick={() => evaluatePrototypeData()}>Evaluate traces</button></div><div className="phase10-validity"><div><strong>{result ? `${result.validity}%` : '—'}</strong><span>Valid generated sequences</span><small>{validCount} passed validation</small></div><div><strong>{result ? `${invalidRate}%` : '—'}</strong><span>Invalid generated sequences</span><small>{invalidCount} rejected · {state.generatedBehaviors.length - validationCount} pending</small></div><div className="phase10-source-legend"><span><i className="source-dot observed"/>Observed trace</span><span><i className="source-dot regenerated"/>Generated behavior</span><span><i className="source-dot replayed"/>Replay trace</span></div></div></section>
    <section className="phase10-chart-grid">{charts.length ? charts.map(([label, value]) => <article className="card phase10-chart" key={label}><span className="section-kicker">OBSERVED VS GENERATED</span><h3>{label}</h3><div className="phase10-compare"><span>Observed</span><i><b style={{ width: '100%' }} /></i><strong>100%</strong></div><div className="phase10-compare"><span>Generated</span><i><b style={{ width: `${value}%` }} /></i><strong>{value}%</strong></div><small>Similarity score</small></article>) : <article className="card phase10-chart phase10-chart-empty"><span className="section-kicker">OBSERVED VS GENERATED</span><h3>Distribution comparison</h3><p>Generate and validate a behavior, then evaluate it to compare action, transition, session-length and timing distributions.</p><a href="/behavior-generator" onClick={(event) => onNavigate(event, '/behavior-generator')}>Open Behavior Generator →</a></article>}</section>
    <section className="card phase10-panel"><div className="phase10-heading"><div><span className="section-kicker">EVALUATION HISTORY</span><h2>Evaluation results</h2><p>Each completed replay also adds a result to this shared evaluation history.</p></div><span className="table-badge">{state.evaluationResults.length} RUNS</span></div><div className="trace-table-wrap"><table className="phase10-table"><thead><tr><th>Evaluation</th><th>Created</th><th>Observed</th><th>Generated</th><th>Replay</th><th>Validity</th><th>Similarity</th><th>Diversity</th><th>Novelty</th><th>ML Utility</th></tr></thead><tbody>{state.evaluationResults.length ? [...state.evaluationResults].reverse().map((row) => <tr key={row.id}><td><strong>{row.id}</strong></td><td>{new Date(row.createdAt).toLocaleString()}</td><td>{row.observedCount}</td><td>{row.generatedCount}</td><td>{row.replayCount}</td><td>{row.validity}%</td><td>{row.similarity}%</td><td>{row.diversity}%</td><td>{row.novelty}%</td><td>+{row.mlUtility}%</td></tr>) : <tr><td colSpan={10} className="phase10-empty">No evaluation yet. Start a validated replay or select “Evaluate traces”.</td></tr>}</tbody></table></div></section>
  </div>
}

function modelScores(result: EvaluationResult | undefined) {
  return models.map((model, index) => result?.models.find((row) => row.model === model) ?? (() => { const baseline = [78, 81, 86, 88][index]; return { model, observedOnly: { accuracy: baseline, precision: baseline - 2, recall: baseline - 4, f1: baseline - 3 }, augmented: { accuracy: baseline + 3, precision: baseline + 2, recall: baseline + 1, f1: baseline + 2 } } })())
}

export function MLAnalysisPage() {
  const state = usePrototypeState(); const result = latestResult(state.evaluationResults); const rows = modelScores(result)
  return <div className="phase10-page"><section className="card phase10-overview"><div><span className="section-kicker">ML DATA UTILITY</span><h2>Observed-only vs augmented dataset</h2><p>Mock evaluation estimates illustrate how generated traces may change model utility. Models are not trained in this prototype.</p></div><div className="phase10-overview-meta"><span><small>OBSERVED EVENTS</small><strong>{result?.observedCount ?? state.traceEvents.length}</strong></span><span><small>GENERATED ACTIONS</small><strong>{result?.generatedCount ?? state.generatedBehaviors.reduce((n, item) => n + item.generatedActions.length, 0)}</strong></span><span><small>REPLAY ROWS</small><strong>{result?.replayCount ?? state.generatedTraces.length}</strong></span></div></section>
    <section className="card phase10-panel"><div className="phase10-heading"><div><span className="section-kicker">MODEL COMPARISON</span><h2>Classification metrics</h2><p>Observed Only compared with Observed + Generated for each model.</p></div><span className="table-badge phase10-estimate-badge">SIMULATED ESTIMATE</span></div><div className="trace-table-wrap"><table className="phase10-table phase10-model-table"><thead><tr><th rowSpan={2}>Model</th><th colSpan={4}>Observed Only</th><th colSpan={4}>Observed + Generated</th></tr><tr>{[...metricKeys,...metricKeys].map((key,index)=><th key={`${key}-${index}`}>{key.toUpperCase()}</th>)}</tr></thead><tbody>{rows.map((row)=><tr key={row.model}><td><strong>{row.model}</strong></td>{metricKeys.map(key=><td key={`o-${key}`}>{row.observedOnly[key]}%</td>)}{metricKeys.map(key=><td className="phase10-augmented" key={`a-${key}`}>{row.augmented[key]}%</td>)}</tr>)}</tbody></table></div></section>
    <section className="phase10-model-cards">{rows.map((row)=><article className="card phase10-model-card" key={row.model}><span className="section-kicker">{row.model.toUpperCase()}</span><h3>F1 score</h3><div className="phase10-compare"><span>Observed only</span><i><b style={{width:`${row.observedOnly.f1}%`}}/></i><strong>{row.observedOnly.f1}%</strong></div><div className="phase10-compare"><span>Observed + generated</span><i><b className="augmented-fill" style={{width:`${row.augmented.f1}%`}}/></i><strong>{row.augmented.f1}%</strong></div></article>)}</section>
  </div>
}

function buildDatasetRecords(state: PrototypeState): DatasetRecord[] {
  const runFor = (id: string) => state.runs.find((run) => run.id === id)
  const sessions: DatasetRecord[] = state.sessions.map((session) => {
    const events = state.traceEvents.filter((event) => event.sessionId === session.id)
    const run = runFor(session.runId); const protocol = events.find((event) => event.protocol)?.protocol ?? (session.service.includes('MQTT') ? 'MQTT' : session.service.includes('SSH') ? 'SSH' : 'Web')
    const stamp = events[0]?.timestamp ?? session.startedAt ?? run?.startTime ?? new Date().toISOString()
    const end = session.endedAt ?? events.at(-1)?.timestamp
    const duration = end ? Math.max(0, Math.round((Date.parse(end) - Date.parse(session.startedAt ?? stamp)) / 1000)) : 0
    return { timestamp: stamp, sourceIp: session.sourceIp, destinationIp: events.find((event) => event.destinationIp)?.destinationIp ?? '192.0.2.10', protocol, sourcePort: events.find((event) => event.sourcePort)?.sourcePort ?? (protocol === 'MQTT' ? 42000 : 50022), destinationPort: events.find((event) => event.destinationPort)?.destinationPort ?? (protocol === 'MQTT' ? 1883 : protocol === 'SSH' ? 22 : 80), packetCount: events.length, byteCount: events.reduce((n, event) => n + (event.packetSize ?? 0), 0), connectionCount: 1, mqttPublishCount: events.filter((event) => event.action === 'mqtt_publish').length, mqttSubscribeCount: events.filter((event) => event.action === 'mqtt_subscribe').length, loginAttempt: events.filter((event) => event.action === 'login_attempt').length, sessionDuration: duration, topic: events.find((event) => event.topic)?.topic ?? (protocol === 'MQTT' ? 'devices/esp32-01/#' : '—'), scenarioId: run?.scenarioId ?? run?.id ?? '—', attackType: session.attackType, label: run?.kind === 'Normal' ? 'Normal' : run ? 'Attack' : 'Unknown', source: events[0]?.source ?? 'observed_real' }
  })
  const regenerated: DatasetRecord[] = state.generatedBehaviors.map((generation) => {
    const session = state.sessions.find((item) => item.id === generation.sourceSessionId); const run = runFor(generation.runId); const protocol = generation.generatedActions.some((action) => action.startsWith('mqtt_') || action === 'topic_discovery') ? 'MQTT' : session?.service.includes('SSH') ? 'SSH' : 'Web'
    return { timestamp: generation.createdAt, sourceIp: session?.sourceIp ?? '198.51.100.42', destinationIp: '192.0.2.10', protocol, sourcePort: 42000, destinationPort: protocol === 'MQTT' ? 1883 : protocol === 'SSH' ? 22 : 80, packetCount: generation.generatedActions.length, byteCount: generation.generatedActions.length * 256, connectionCount: generation.generatedActions.some((action) => action.endsWith('connect')) ? 1 : 0, mqttPublishCount: generation.generatedActions.filter((action) => action === 'mqtt_publish').length, mqttSubscribeCount: generation.generatedActions.filter((action) => action === 'mqtt_subscribe').length, loginAttempt: generation.generatedActions.filter((action) => action === 'login_attempt').length, sessionDuration: generation.timingMs.reduce((sum, ms) => sum + ms, 0) / 1000, topic: protocol === 'MQTT' ? 'devices/esp32-01/#' : '—', scenarioId: run?.scenarioId ?? run?.id ?? '—', attackType: run?.attackType ?? 'Generated behavior', label: run?.kind === 'Normal' ? 'Normal' : 'Attack', source: 'regenerated' }
  })
  const replayed: DatasetRecord[] = state.replays.map((replay) => {
    const traces = state.generatedTraces.filter((trace) => trace.replayId === replay.id); const generation = state.generatedBehaviors.find((item) => item.id === replay.generationId); const run = runFor(replay.runId); const session = generation && state.sessions.find((item) => item.id === generation.sourceSessionId)
    return { timestamp: traces[0]?.timestamp ?? replay.startedAt, sourceIp: session?.sourceIp ?? '198.51.100.42', destinationIp: '192.0.2.10', protocol: replay.protocol, sourcePort: 42000, destinationPort: replay.protocol === 'MQTT' ? 1883 : replay.protocol === 'SSH' ? 22 : 80, packetCount: traces.length, byteCount: traces.length * 256, connectionCount: traces.length ? 1 : 0, mqttPublishCount: traces.filter((trace) => trace.action === 'mqtt_publish').length, mqttSubscribeCount: traces.filter((trace) => trace.action === 'mqtt_subscribe').length, loginAttempt: traces.filter((trace) => trace.action === 'login_attempt').length, sessionDuration: traces.length > 1 ? Math.max(0, (Date.parse(traces.at(-1)!.timestamp) - Date.parse(traces[0].timestamp)) / 1000) : 0, topic: replay.protocol === 'MQTT' ? 'devices/esp32-01/#' : '—', scenarioId: run?.scenarioId ?? run?.id ?? '—', attackType: run?.attackType ?? 'Replayed behavior', label: run?.kind === 'Normal' ? 'Normal' : 'Attack', source: 'replayed' }
  })
  return [...sessions, ...regenerated, ...replayed].sort((a,b)=>b.timestamp.localeCompare(a.timestamp))
}

const columns: {key:keyof DatasetRecord;label:string}[] = [
  {key:'timestamp',label:'Timestamp'},{key:'sourceIp',label:'Source IP'},{key:'destinationIp',label:'Destination IP'},{key:'protocol',label:'Protocol'},{key:'sourcePort',label:'Source Port'},{key:'destinationPort',label:'Destination Port'},{key:'packetCount',label:'Packet Count'},{key:'byteCount',label:'Byte Count'},{key:'connectionCount',label:'Connection Count'},{key:'mqttPublishCount',label:'MQTT Publish Count'},{key:'mqttSubscribeCount',label:'MQTT Subscribe Count'},{key:'loginAttempt',label:'Login Attempt'},{key:'sessionDuration',label:'Session Duration (s)'},{key:'topic',label:'Topic'},{key:'scenarioId',label:'Scenario ID'},{key:'attackType',label:'Attack Type'},{key:'label',label:'Label'},{key:'source',label:'Source'},
]
function download(name: string, content: string, mime: string) { const url = URL.createObjectURL(new Blob([content],{type:mime})); const anchor = document.createElement('a'); anchor.href=url; anchor.download=name; anchor.hidden=true; document.body.appendChild(anchor); anchor.click(); anchor.remove(); window.setTimeout(()=>URL.revokeObjectURL(url),1000) }
function csvEscape(value: unknown) { const text=String(value); return /[",\r\n]/.test(text) ? `"${text.replaceAll('"','""')}"` : text }
function datasetAsCsv(rows: DatasetRecord[]) { return '\uFEFF'+[columns.map(c=>c.label).join(','),...rows.map(row=>columns.map(c=>csvEscape(row[c.key])).join(','))].join('\r\n') }
function datasetAsJson(rows: DatasetRecord[]) { return JSON.stringify(rows,null,2) }

export function DatasetPage() {
  const state=usePrototypeState(); const [source,setSource]=useState('all'); const [label,setLabel]=useState('all'); const [search,setSearch]=useState('')
  const allRows=useMemo(()=>buildDatasetRecords(state),[state]); const rows=allRows.filter((row)=>(source==='all'||row.source===source)&&(label==='all'||row.label===label)&&(!search||Object.values(row).join(' ').toLowerCase().includes(search.toLowerCase())))
  const exportRows=(format:'csv'|'json')=>{const stamp=new Date().toISOString().slice(0,10);if(format==='json')download(`tracelab-dataset-${stamp}.json`,datasetAsJson(rows),'application/json');else download(`tracelab-dataset-${stamp}.csv`,datasetAsCsv(rows),'text/csv;charset=utf-8')}
  return <div className="phase10-page"><section className="card phase10-overview"><div><span className="section-kicker">TRACE DATASET</span><h2>Source-aware research dataset</h2><p>Session aggregates and behavior outputs remain labeled as observed, simulated, regenerated or replayed.</p></div><div className="phase10-overview-meta"><span><small>DATASET ROWS</small><strong>{allRows.length}</strong></span><span><small>OBSERVED EVENTS</small><strong>{state.traceEvents.filter((event)=>event.source==='observed_real').length}</strong></span><span><small>REPLAY TRACES</small><strong>{state.generatedTraces.length}</strong></span></div></section>
    <section className="card phase10-panel"><div className="phase10-heading"><div><span className="section-kicker">CURATED RECORDS</span><h2>Dataset records</h2><p>{rows.length} of {allRows.length} records match the selected filters.</p></div><div className="phase10-export"><button className="button button-secondary" onClick={()=>exportRows('csv')}>Export CSV</button><button className="button button-primary" onClick={()=>exportRows('json')}>Export JSON</button></div></div><div className="phase10-filters"><input aria-label="Search dataset" placeholder="Search IP, topic, scenario…" value={search} onChange={(event)=>setSearch(event.target.value)}/><select aria-label="Filter source" value={source} onChange={(event)=>setSource(event.target.value)}><option value="all">All sources</option><option value="observed_real">Observed real</option><option value="simulated">Simulated</option><option value="regenerated">Regenerated</option><option value="replayed">Replayed</option></select><select aria-label="Filter label" value={label} onChange={(event)=>setLabel(event.target.value)}><option value="all">All labels</option><option>Normal</option><option>Attack</option><option>Unknown</option></select></div><div className="trace-table-wrap phase10-dataset-wrap"><table className="phase10-table phase10-dataset-table"><thead><tr>{columns.map((column)=><th key={column.key}>{column.label}</th>)}</tr></thead><tbody>{rows.map((row,index)=><tr key={`${row.source}-${row.timestamp}-${index}`}>{columns.map((column)=><td key={column.key}>{column.key==='timestamp'?new Date(String(row[column.key])).toLocaleString():column.key==='source'?<span className={`trace-source trace-source-${row.source}`}>{row.source}</span>:String(row[column.key])}</td>)}</tr>)}{!rows.length&&<tr><td colSpan={columns.length} className="phase10-empty">No dataset records match these filters.</td></tr>}</tbody></table></div></section>
  </div>
}
